<?php

use Illuminate\Database\Seeder;


class CountrySeeder extends Seeder
{

    public function run()
    {

        $data = array(        

            array('code' => 'ZA', 'description' => 'South Africa', 'currency_code' => 'ZAR', 'currency_name' => 'Rand', 'created_at' => date("Y-m-d H:i:s")),        
            array('code' => 'AF', 'description' => 'Afghanistan', 'currency_code' => 'AFN', 'currency_name' => 'Afghani', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AX', 'description' => 'Aland Islands', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AL', 'description' => 'Albania', 'currency_code' => 'ALL', 'currency_name' => 'Lek', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'DZ', 'description' => 'Algeria', 'currency_code' => 'DZD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AS', 'description' => 'American Samoa', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AD', 'description' => 'Andorra', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AO', 'description' => 'Angola', 'currency_code' => 'AOA', 'currency_name' => 'Kwanza', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AI', 'description' => 'Anguilla', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AG', 'description' => 'Antigua and Barbuda', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AR', 'description' => 'Argentina', 'currency_code' => 'ARS', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AM', 'description' => 'Armenia', 'currency_code' => 'AMD', 'currency_name' => 'Dram', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AW', 'description' => 'Aruba', 'currency_code' => 'AWG', 'currency_name' => 'Guilder', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AU', 'description' => 'Australia', 'currency_code' => 'AUD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AT', 'description' => 'Austria', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AZ', 'description' => 'Azerbaijan', 'currency_code' => 'AZN', 'currency_name' => 'Manat', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BS', 'description' => 'Bahamas', 'currency_code' => 'BSD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BH', 'description' => 'Bahrain', 'currency_code' => 'BHD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BD', 'description' => 'Bangladesh', 'currency_code' => 'BDT', 'currency_name' => 'Taka', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BB', 'description' => 'Barbados', 'currency_code' => 'BBD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BY', 'description' => 'Belarus', 'currency_code' => 'BYR', 'currency_name' => 'Ruble', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BE', 'description' => 'Belgium', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BZ', 'description' => 'Belize', 'currency_code' => 'BZD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BJ', 'description' => 'Benin', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BM', 'description' => 'Bermuda', 'currency_code' => 'BMD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BT', 'description' => 'Bhutan', 'currency_code' => 'BTN', 'currency_name' => 'Ngultrum', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BO', 'description' => 'Bolivia', 'currency_code' => 'BOB', 'currency_name' => 'Boliviano', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BA', 'description' => 'Bosnia and Herzegovina', 'currency_code' => 'BAM', 'currency_name' => 'Marka', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BW', 'description' => 'Botswana', 'currency_code' => 'BWP', 'currency_name' => 'Pula', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BR', 'description' => 'Brazil', 'currency_code' => 'BRL', 'currency_name' => 'Real', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'VG', 'description' => 'British Virgin Islands', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BN', 'description' => 'Brunei', 'currency_code' => 'BND', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BG', 'description' => 'Bulgaria', 'currency_code' => 'BGN', 'currency_name' => 'Lev', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BF', 'description' => 'Burkina Faso', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'BI', 'description' => 'Burundi', 'currency_code' => 'BIF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KH', 'description' => 'Cambodia', 'currency_code' => 'KHR', 'currency_name' => 'Riels', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CM', 'description' => 'Cameroon', 'currency_code' => 'XAF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CA', 'description' => 'Canada', 'currency_code' => 'CAD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CV', 'description' => 'Cape Verde', 'currency_code' => 'CVE', 'currency_name' => 'Escudo', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KY', 'description' => 'Cayman Islands', 'currency_code' => 'KYD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CF', 'description' => 'Central African Republic', 'currency_code' => 'XAF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TD', 'description' => 'Chad', 'currency_code' => 'XAF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CL', 'description' => 'Chile', 'currency_code' => 'CLP', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CN', 'description' => 'China', 'currency_code' =>'CNY', 'currency_name' =>'Yuan Renminbi', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CX', 'description' => 'Christmas Island', 'currency_code' => 'AUD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CO', 'description' => 'Colombia', 'currency_code' => 'COP', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KM', 'description' => 'Comoros', 'currency_code' => 'KMF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CK', 'description' => 'Cook Islands', 'currency_code' => 'NZD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CR', 'description' => 'Costa Rica', 'currency_code' => 'CRC', 'currency_name' => 'Colon', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'HR', 'description' => 'Croatia', 'currency_code' => 'HRK', 'currency_name' => 'Kuna', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CU', 'description' => 'Cuba', 'currency_code' => 'CUP', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CW', 'description' => 'Curacao', 'currency_code' => 'ANG', 'currency_name' => 'Guilder', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CY', 'description' => 'Cyprus', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CZ', 'description' => 'Czech Republic', 'currency_code' => 'CZK', 'currency_name' => 'Koruna', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CD', 'description' => 'Democratic Republic of the Congo', 'currency_code' => 'CDF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'DK', 'description' => 'Denmark', 'currency_code' => 'DKK', 'currency_name' => 'Krone', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'DJ', 'description' => 'Djibouti', 'currency_code' => 'DJF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'DM', 'description' => 'Dominica', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'DO', 'description' => 'Dominican Republic', 'currency_code' => 'DOP', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TL', 'description' => 'East Timor', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'EC', 'description' => 'Ecuador', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'EG', 'description' => 'Egypt', 'currency_code' => 'EGP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SV', 'description' => 'El Salvador', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GQ', 'description' => 'Equatorial Guinea', 'currency_code' => 'XAF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ER', 'description' => 'Eritrea', 'currency_code' => 'ERN', 'currency_name' => 'Nakfa', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'EE', 'description' => 'Estonia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ET', 'description' => 'Ethiopia', 'currency_code' => 'ETB', 'currency_name' => 'Birr', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'FK', 'description' => 'Falkland Islands', 'currency_code' => 'FKP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'FO', 'description' => 'Faroe Islands', 'currency_code' => 'DKK', 'currency_name' => 'Krone', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'FJ', 'description' => 'Fiji', 'currency_code' => 'FJD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'FI', 'description' => 'Finland', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'FR', 'description' => 'France', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GF', 'description' => 'French Guiana', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PF', 'description' => 'French Polynesia', 'currency_code' => 'XPF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GA', 'description' => 'Gabon', 'currency_code' => 'XAF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GM', 'description' => 'Gambia', 'currency_code' => 'GMD', 'currency_name' => 'Dalasi', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GE', 'description' => 'Georgia', 'currency_code' => 'GEL', 'currency_name' => 'Lari', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'DE', 'description' => 'Germany', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GH', 'description' => 'Ghana', 'currency_code' => 'GHS', 'currency_name' => 'Cedi', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GI', 'description' => 'Gibraltar', 'currency_code' => 'GIP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GR', 'description' => 'Greece', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GL', 'description' => 'Greenland', 'currency_code' => 'DKK', 'currency_name' => 'Krone', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GD', 'description' => 'Grenada', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GP', 'description' => 'Guadeloupe', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GU', 'description' => 'Guam', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GT', 'description' => 'Guatemala', 'currency_code' => 'GTQ', 'currency_name' => 'Quetzal', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GG', 'description' => 'Guernsey', 'currency_code' => 'GBP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GN', 'description' => 'Guinea', 'currency_code' => 'GNF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GW', 'description' => 'Guinea-Bissau', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GY', 'description' => 'Guyana', 'currency_code' => 'GYD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'HT', 'description' => 'Haiti', 'currency_code' => 'HTG', 'currency_name' => 'Gourde', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'HN', 'description' => 'Honduras', 'currency_code' => 'HNL', 'currency_name' => 'Lempira', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'HK', 'description' => 'Hong Kong', 'currency_code' => 'HKD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'HU', 'description' => 'Hungary', 'currency_code' => 'HUF', 'currency_name' => 'Forint', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IS', 'description' => 'Iceland', 'currency_code' => 'ISK', 'currency_name' => 'Krona', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IN', 'description' => 'India', 'currency_code' => 'INR', 'currency_name' => 'Rupee', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ID', 'description' => 'Indonesia', 'currency_code' => 'IDR', 'currency_name' => 'Rupiah', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IR', 'description' => 'Iran', 'currency_code' => 'IRR', 'currency_name' => 'Rial', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IQ', 'description' => 'Iraq', 'currency_code' => 'IQD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IE', 'description' => 'Ireland', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IM', 'description' => 'Isle of Man', 'currency_code' => 'GBP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IL', 'description' => 'Israel', 'currency_code' => 'ILS', 'currency_name' => 'Shekel', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'IT', 'description' => 'Italy', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CI', 'description' => 'Ivory Coast', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'JM', 'description' => 'Jamaica', 'currency_code' => 'JMD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'JP', 'description' => 'Japan', 'currency_code' => 'JPY', 'currency_name' => 'Yen', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'JE', 'description' => 'Jersey', 'currency_code' => 'GBP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'JO', 'description' => 'Jordan', 'currency_code' => 'JOD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KZ', 'description' => 'Kazakhstan', 'currency_code' => 'KZT', 'currency_name' => 'Tenge', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KE', 'description' => 'Kenya', 'currency_code' => 'KES', 'currency_name' => 'Shilling', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KI', 'description' => 'Kiribati', 'currency_code' => 'AUD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'XK', 'description' => 'Kosovo', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KW', 'description' => 'Kuwait', 'currency_code' => 'KWD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KG', 'description' => 'Kyrgyzstan', 'currency_code' => 'KGS', 'currency_name' => 'Som', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LA', 'description' => 'Laos', 'currency_code' => 'LAK', 'currency_name' => 'Kip', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LV', 'description' => 'Latvia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LB', 'description' => 'Lebanon', 'currency_code' => 'LBP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LS', 'description' => 'Lesotho', 'currency_code' => 'LSL', 'currency_name' => 'Loti', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LR', 'description' => 'Liberia', 'currency_code' => 'LRD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LY', 'description' => 'Libya', 'currency_code' => 'LYD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LI', 'description' => 'Liechtenstein', 'currency_code' => 'CHF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LT', 'description' => 'Lithuania', 'currency_code' => 'LTL', 'currency_name' => 'Litas', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LU', 'description' => 'Luxembourg', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MO', 'description' => 'Macao', 'currency_code' => 'MOP', 'currency_name' => 'Pataca', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MK', 'description' => 'Macedonia', 'currency_code' => 'MKD', 'currency_name' => 'Denar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MG', 'description' => 'Madagascar', 'currency_code' => 'MGA', 'currency_name' => 'Ariary', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MW', 'description' => 'Malawi', 'currency_code' => 'MWK', 'currency_name' => 'Kwacha', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MY', 'description' => 'Malaysia', 'currency_code' => 'MYR', 'currency_name' => 'Ringgit', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MV', 'description' => 'Maldives', 'currency_code' => 'MVR', 'currency_name' => 'Rufiyaa', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ML', 'description' => 'Mali', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MT', 'description' => 'Malta', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MH', 'description' => 'Marshall Islands', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MQ', 'description' => 'Martinique', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MR', 'description' => 'Mauritania', 'currency_code' => 'MRO', 'currency_name' => 'Ouguiya', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MU', 'description' => 'Mauritius', 'currency_code' => 'MUR', 'currency_name' => 'Rupee', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'YT', 'description' => 'Mayotte', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MX', 'description' => 'Mexico', 'currency_code' => 'MXN', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'FM', 'description' => 'Micronesia', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MD', 'description' => 'Moldova', 'currency_code' => 'MDL', 'currency_name' => 'Leu', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MC', 'description' => 'Monaco', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MN', 'description' => 'Mongolia', 'currency_code' => 'MNT', 'currency_name' => 'Tugrik', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ME', 'description' => 'Montenegro', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MS', 'description' => 'Montserrat', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MA', 'description' => 'Morocco', 'currency_code' => 'MAD', 'currency_name' => 'Dirham', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MZ', 'description' => 'Mozambique', 'currency_code' => 'MZN', 'currency_name' => 'Metical', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MM', 'description' => 'Myanmar', 'currency_code' => 'MMK', 'currency_name' => 'Kyat', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NA', 'description' => 'Namibia', 'currency_code' => 'NAD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NR', 'description' => 'Nauru', 'currency_code' => 'AUD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NP', 'description' => 'Nepal', 'currency_code' => 'NPR', 'currency_name' => 'Rupee', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NL', 'description' => 'Netherlands', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NC', 'description' => 'New Caledonia', 'currency_code' => 'XPF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NZ', 'description' => 'New Zealand', 'currency_code' => 'NZD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NI', 'description' => 'Nicaragua', 'currency_code' => 'NIO', 'currency_name' => 'Cordoba', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NE', 'description' => 'Niger', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NG', 'description' => 'Nigeria', 'currency_code' => 'NGN', 'currency_name' => 'Naira', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NU', 'description' => 'Niue', 'currency_code' => 'NZD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NF', 'description' => 'Norfolk Island', 'currency_code' => 'AUD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KP', 'description' => 'North Korea', 'currency_code' => 'KPW', 'currency_name' => 'Won', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MP', 'description' => 'Northern Mariana Islands', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'NO', 'description' => 'Norway', 'currency_code' => 'NOK', 'currency_name' => 'Krone', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'OM', 'description' => 'Oman', 'currency_code' => 'OMR', 'currency_name' => 'Rial', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PK', 'description' => 'Pakistan', 'currency_code' => 'PKR', 'currency_name' => 'Rupee', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PW', 'description' => 'Palau', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PS', 'description' => 'Palestinian Territory', 'currency_code' => 'ILS', 'currency_name' => 'Shekel', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PA', 'description' => 'Panama', 'currency_code' => 'PAB', 'currency_name' => 'Balboa', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PG', 'description' => 'Papua New Guinea', 'currency_code' => 'PGK', 'currency_name' => 'Kina', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PY', 'description' => 'Paraguay', 'currency_code' => 'PYG', 'currency_name' => 'Guarani', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PE', 'description' => 'Peru', 'currency_code' => 'PEN', 'currency_name' => 'Sol', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PH', 'description' => 'Philippines', 'currency_code' => 'PHP', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PN', 'description' => 'Pitcairn', 'currency_code' => 'NZD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PL', 'description' => 'Poland', 'currency_code' => 'PLN', 'currency_name' => 'Zloty', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PT', 'description' => 'Portugal', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PR', 'description' => 'Puerto Rico', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'QA', 'description' => 'Qatar', 'currency_code' => 'QAR', 'currency_name' => 'Rial', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CG', 'description' => 'Republic of the Congo', 'currency_code' => 'XAF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'RE', 'description' => 'Reunion', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'RO', 'description' => 'Romania', 'currency_code' => 'RON', 'currency_name' => 'Leu', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'RU', 'description' => 'Russia', 'currency_code' => 'RUB', 'currency_name' => 'Ruble', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'RW', 'description' => 'Rwanda', 'currency_code' => 'RWF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KN', 'description' => 'Saint Kitts and Nevis', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LC', 'description' => 'Saint Lucia', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'MF', 'description' => 'Saint Martin', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'PM', 'description' => 'Saint Pierre and Miquelon', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'VC', 'description' => 'St Vincent and the Grenadines', 'currency_code' => 'XCD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'WS', 'description' => 'Samoa', 'currency_code' => 'WST', 'currency_name' => 'Tala', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SM', 'description' => 'San Marino', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ST', 'description' => 'Sao Tome and Principe', 'currency_code' => 'STD', 'currency_name' => 'Dobra', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SA', 'description' => 'Saudi Arabia', 'currency_code' => 'SAR', 'currency_name' => 'Rial', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SN', 'description' => 'Senegal', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'RS', 'description' => 'Serbia', 'currency_code' => 'RSD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CS', 'description' => 'Serbia and Montenegro', 'currency_code' => 'RSD', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SC', 'description' => 'Seychelles', 'currency_code' => 'SCR', 'currency_name' => 'Rupee', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SL', 'description' => 'Sierra Leone', 'currency_code' => 'SLL', 'currency_name' => 'Leone', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SG', 'description' => 'Singapore', 'currency_code' => 'SGD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SX', 'description' => 'Sint Maarten', 'currency_code' => 'ANG', 'currency_name' => 'Guilder', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SK', 'description' => 'Slovakia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SI', 'description' => 'Slovenia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SB', 'description' => 'Solomon Islands', 'currency_code' => 'SBD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SO', 'description' => 'Somalia', 'currency_code' => 'SOS', 'currency_name' => 'Shilling', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GS', 'description' => 'South Georgia', 'currency_code' => 'GBP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'KR', 'description' => 'South Korea', 'currency_code' => 'KRW', 'currency_name' => 'Won', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SS', 'description' => 'South Sudan', 'currency_code' => 'SSP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ES', 'description' => 'Spain', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'LK', 'description' => 'Sri Lanka', 'currency_code' => 'LKR', 'currency_name' => 'Rupee', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SD', 'description' => 'Sudan', 'currency_code' => 'SDG', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SR', 'description' => 'Suriname', 'currency_code' => 'SRD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SZ', 'description' => 'Swaziland', 'currency_code' => 'SZL', 'currency_name' => 'Lilangeni', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SE', 'description' => 'Sweden', 'currency_code' => 'SEK', 'currency_name' => 'Krona', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'CH', 'description' => 'Switzerland', 'currency_code' => 'CHF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'SY', 'description' => 'Syria', 'currency_code' => 'SYP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TW', 'description' => 'Taiwan', 'currency_code' => 'TWD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TJ', 'description' => 'Tajikistan', 'currency_code' => 'TJS', 'currency_name' => 'Somoni', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TZ', 'description' => 'Tanzania', 'currency_code' => 'TZS', 'currency_name' => 'Shilling', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TH', 'description' => 'Thailand', 'currency_code' => 'THB', 'currency_name' => 'Baht', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TG', 'description' => 'Togo', 'currency_code' => 'XOF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TO', 'description' => 'Tonga', 'currency_code' =>'TOP', 'currency_name' =>'Pa anga', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TT', 'description' => 'Trinidad and Tobago', 'currency_code' => 'TTD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TN', 'description' => 'Tunisia', 'currency_code' => 'TND', 'currency_name' => 'Dinar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TR', 'description' => 'Turkey', 'currency_code' => 'TRY', 'currency_name' => 'Lira', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TM', 'description' => 'Turkmenistan', 'currency_code' => 'TMT', 'currency_name' => 'Manat', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TC', 'description' => 'Turks and Caicos Islands', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'TV', 'description' => 'Tuvalu', 'currency_code' => 'AUD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'VI', 'description' => 'U.S. Virgin Islands', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'UG', 'description' => 'Uganda', 'currency_code' => 'UGX', 'currency_name' => 'Shilling', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'UA', 'description' => 'Ukraine', 'currency_code' => 'UAH', 'currency_name' => 'Hryvnia', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'AE', 'description' => 'United Arab Emirates', 'currency_code' => 'AED', 'currency_name' => 'Dirham', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'GB', 'description' => 'United Kingdom', 'currency_code' => 'GBP', 'currency_name' => 'Pound', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'US', 'description' => 'United States', 'currency_code' => 'USD', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'UY', 'description' => 'Uruguay', 'currency_code' => 'UYU', 'currency_name' => 'Peso', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'UZ', 'description' => 'Uzbekistan', 'currency_code' => 'UZS', 'currency_name' => 'Som', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'VU', 'description' => 'Vanuatu', 'currency_code' => 'VUV', 'currency_name' => 'Vatu', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'VA', 'description' => 'Vatican', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'VE', 'description' => 'Venezuela', 'currency_code' => 'VEF', 'currency_name' => 'Bolivar', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'VN', 'description' => 'Vietnam', 'currency_code' => 'VND', 'currency_name' => 'Dong', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'WF', 'description' => 'Wallis and Futuna', 'currency_code' => 'XPF', 'currency_name' => 'Franc', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'EH', 'description' => 'Western Sahara', 'currency_code' => 'MAD', 'currency_name' => 'Dirham', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'YE', 'description' => 'Yemen', 'currency_code' => 'YER', 'currency_name' => 'Rial', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ZM', 'description' => 'Zambia', 'currency_code' => 'ZMW', 'currency_name' => 'Kwacha', 'created_at' => date("Y-m-d H:i:s")),
            array('code' => 'ZW', 'description' => 'Zimbabwe', 'currency_code' => 'ZWL', 'currency_name' => 'Dollar', 'created_at' => date("Y-m-d H:i:s")),

        );

        DB::table('countries')->insert($data);       


    }
}
