<?php

use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    public function run()
    {
        $data = [

            ['countryCode' => 'ZA', 'code' => 'NL', 'description' => 'Kwazulu-Natal'],
            ['countryCode' => 'ZA', 'code' => 'GT', 'description' => 'Gauteng'],
            ['countryCode' => 'ZA', 'code' => 'FS', 'description' => 'Free State'],
            ['countryCode' => 'ZA', 'code' => 'EC', 'description' => 'Eastern Cape'],
            ['countryCode' => 'ZA', 'code' => 'LP', 'description' => 'Limpopo'],
            ['countryCode' => 'ZA', 'code' => 'MP', 'description' => 'Mpumalanga'],
            ['countryCode' => 'ZA', 'code' => 'NC', 'description' => 'Northern Cape'],
            ['countryCode' => 'ZA', 'code' => 'NW', 'description' => 'North-West'],
            ['countryCode' => 'ZA', 'code' => 'WC', 'description' => 'Western Cape'],

            ['countryCode' => 'US', 'code' => 'AL', 'description' => 'Alabama'],
            ['countryCode' => 'US', 'code' => 'AK', 'description' => 'Alaska'],
            ['countryCode' => 'US', 'code' => 'AZ', 'description' => 'Arizona'],
            ['countryCode' => 'US', 'code' => 'AR', 'description' => 'Arkansas'],
            ['countryCode' => 'US', 'code' => 'CA', 'description' => 'California'],
            ['countryCode' => 'US', 'code' => 'CO', 'description' => 'Colorado'],
            ['countryCode' => 'US', 'code' => 'CT', 'description' => 'Connecticut'],
            ['countryCode' => 'US', 'code' => 'DE', 'description' => 'Delaware'],
            ['countryCode' => 'US', 'code' => 'DC', 'description' => 'District Of Columbia'],
            ['countryCode' => 'US', 'code' => 'FL', 'description' => 'Florida'],
            ['countryCode' => 'US', 'code' => 'GA', 'description' => 'Georgia'],
            ['countryCode' => 'US', 'code' => 'HI', 'description' => 'Hawaii'],
            ['countryCode' => 'US', 'code' => 'ID', 'description' => 'Idaho'],
            ['countryCode' => 'US', 'code' => 'IL', 'description' => 'Illinois'],
            ['countryCode' => 'US', 'code' => 'IN', 'description' => 'Indiana'],
            ['countryCode' => 'US', 'code' => 'IA', 'description' => 'Iowa'],
            ['countryCode' => 'US', 'code' => 'KS', 'description' => 'Kansas'],
            ['countryCode' => 'US', 'code' => 'KY', 'description' => 'Kentucky'],
            ['countryCode' => 'US', 'code' => 'LA', 'description' => 'Louisiana'],
            ['countryCode' => 'US', 'code' => 'ME', 'description' => 'Maine'],
            ['countryCode' => 'US', 'code' => 'MD', 'description' => 'Maryland'],
            ['countryCode' => 'US', 'code' => 'MA', 'description' => 'Massachusetts'],
            ['countryCode' => 'US', 'code' => 'MI', 'description' => 'Michigan'],
            ['countryCode' => 'US', 'code' => 'MN', 'description' => 'Minnesota'],
            ['countryCode' => 'US', 'code' => 'MS', 'description' => 'Mississippi'],
            ['countryCode' => 'US', 'code' => 'MO', 'description' => 'Missouri'],
            ['countryCode' => 'US', 'code' => 'MT', 'description' => 'Montana'],
            ['countryCode' => 'US', 'code' => 'NE', 'description' => 'Nebraska'],
            ['countryCode' => 'US', 'code' => 'NV', 'description' => 'Nevada'],
            ['countryCode' => 'US', 'code' => 'NH', 'description' => 'New Hampshire'],
            ['countryCode' => 'US', 'code' => 'NJ', 'description' => 'New Jersey'],
            ['countryCode' => 'US', 'code' => 'NM', 'description' => 'New Mexico'],
            ['countryCode' => 'US', 'code' => 'NY', 'description' => 'New York'],
            ['countryCode' => 'US', 'code' => 'NC', 'description' => 'North Carolina'],
            ['countryCode' => 'US', 'code' => 'ND', 'description' => 'North Dakota'],
            ['countryCode' => 'US', 'code' => 'OH', 'description' => 'Ohio'],
            ['countryCode' => 'US', 'code' => 'OK', 'description' => 'Oklahoma'],
            ['countryCode' => 'US', 'code' => 'OR', 'description' => 'Oregon'],
            ['countryCode' => 'US', 'code' => 'PA', 'description' => 'Pennsylvania'],
            ['countryCode' => 'US', 'code' => 'RI', 'description' => 'Rhode Island'],
            ['countryCode' => 'US', 'code' => 'SC', 'description' => 'South Carolina'],
            ['countryCode' => 'US', 'code' => 'SD', 'description' => 'South Dakota'],
            ['countryCode' => 'US', 'code' => 'TN', 'description' => 'Tennessee'],
            ['countryCode' => 'US', 'code' => 'TX', 'description' => 'Texas'],
            ['countryCode' => 'US', 'code' => 'UT', 'description' => 'Utah'],
            ['countryCode' => 'US', 'code' => 'VT', 'description' => 'Vermont'],
            ['countryCode' => 'US', 'code' => 'VA', 'description' => 'Virginia'],
            ['countryCode' => 'US', 'code' => 'WA', 'description' => 'Washington'],
            ['countryCode' => 'US', 'code' => 'WV', 'description' => 'West Virginia'],
            ['countryCode' => 'US', 'code' => 'WI', 'description' => 'Wisconsin'],
            ['countryCode' => 'US', 'code' => 'WY', 'description' => 'Wyoming'],

            //Canada
            ['countryCode' => 'CA', 'code' => 'AB', 'description' => 'Alberta'],
            ['countryCode' => 'CA', 'code' => 'BC', 'description' => 'British Columbia'],
            ['countryCode' => 'CA', 'code' => 'MB', 'description' => 'Manitoba'],
            ['countryCode' => 'CA', 'code' => 'NB', 'description' => 'New Brunswick'],
            ['countryCode' => 'CA', 'code' => 'NL', 'description' => 'Newfoundland and Labrador'],
            ['countryCode' => 'CA', 'code' => 'NS', 'description' => 'Nova Scotia'],
            ['countryCode' => 'CA', 'code' => 'ON', 'description' => 'Ontario'],
            ['countryCode' => 'CA', 'code' => 'PE', 'description' => 'Prince Edward Island'],
            ['countryCode' => 'CA', 'code' => 'QC', 'description' => 'Quebec'],
            ['countryCode' => 'CA', 'code' => 'SK', 'description' => 'Saskatchewan'],
            ['countryCode' => 'CA', 'code' => 'NT', 'description' => 'Northwest Territories'],
            ['countryCode' => 'CA', 'code' => 'NU', 'description' => 'Nunavut'],
            ['countryCode' => 'CA', 'code' => 'YT', 'description' => 'Yukon'],

            // Other Countries
            ['countryCode' => 'AF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AX', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'DZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AD', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BD', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BB', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BJ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'VG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'BI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CV', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TD', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CX', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'HR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CD', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'DK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'DJ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'DM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'DO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'EC', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'EG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SV', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GQ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ER', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'EE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ET', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'FK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'FO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'FJ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'FI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'FR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'DE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GD', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GP', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'HT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'HN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'HK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'HU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ID', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IQ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'IT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'JM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'JP', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'JE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'JO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'XK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LV', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LB', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MV', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ML', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MQ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'YT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MX', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'FM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MD', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MC', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ME', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NP', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NC', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KP', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MP', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'NO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'OM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'QA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'RE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'RO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'RU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'RW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LC', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'MF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'PM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'VC', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'WS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ST', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'RS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SC', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SL', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SX', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SB', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'KR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SS', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ES', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'LK', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SD', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'CH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'SY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TW', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TJ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TO', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TT', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TR', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TC', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'TV', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'VI', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'UG', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'UA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'AE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'GB', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'UY', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'UZ', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'VU', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'VA', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'VE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'VN', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'WF', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'EH', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'YE', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ZM', 'description' => 'n/a ', 'code' => 'NA'],
            ['countryCode' => 'ZW', 'description' => 'n/a ', 'code' => 'NA'],

        ];

        DB::table('provinces')->insert($data);
    }
}
