<template>

<div :id="id" class="card h-100 border-0">
    
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <h3><i class="fa fa-cog mr-2"></i>System Settings</h3>
        </div>
    </div>



    <div class="card-body form-tab-body overflow-auto">

        <form-tabs :tabs="tabs"/>

        <div v-show="activeTab === 'LetterHead'" class="form-tab-content">
            <div v-show="!letterHeadPdfFile" class="row mt-3">

                <div class="col-md-12">

                    <letterhead-dropzone 
                        v-show="!letterHeadPdfFile"
                        id="company-letterhead-drop-zone-component" 
                        ref="company-letterhead-drop-zone-component" 
                        :options="letterHeadDropOptions" 
                        :useCustomSlot=true 
                        @vdropzone-error="letterHeadUploadError"
                        @vdropzone-success="letterHeadUploaded"
                    >
                        <div class="dropzone-custom-content cp">
                            <h1 class="text-primary" style="display:inline-block">Company Letterhead</h1>
                            <h2 style="display:inline-block">
                                <pop-over content="
                                    <h4>Company Letterhead</h4>
                                    <p>A letterhead can be used in documents generated by the program.</p> 
                                        <p>Instead of putting the letterhead in every Document Template, you can design your letterhead once (in Word) and then upload it here. 
                                        You can then insert it into a Document Template using a Component [letterhead].</p>
                                    <p>If your letterhead ever changes, you can replace it here and the documents will then use this new letterhead going forward.</p>" 
                                    :container="'#' + id"
                                />
                            </h2>

                            
                            <h3 class="text-success mt-5">Drag and drop your letterhead here</h3>
                            <div class="subtitle">...or click anywhere in this box to manually select a document</div>
                        </div>
                    </letterhead-dropzone>

                </div>

            </div>

            <div v-show="letterHeadPdfFile" class="row mt-3">
                <div class="col-md-12">
                    <div class="d-flex justify-content-between">
                        <div>
                            <h4>Letterhead</h4>
                        </div>
                        <div>
                            <button class="btn btn-secondary btn-sm d-inline-block mr-2" @click="replaceLetterHead" title="Replace the Letterhead"><i class="fa fa-refresh mr-2"></i>Replace</button>
                            <button class="btn btn-primary btn-sm d-inline-block mr-2" @click="downloadLetterHead" title="Download the Letterhead"><i class="fa fa-download mr-2"></i>Download</button>
                            <button class="btn btn-danger btn-sm d-inline-block" @click="deleteLetterHead" title="Delete the Letterhead"><i class="fa fa-times mr-2"></i>Delete</button>
                        </div>
                    </div>
                </div>
            </div>


            <div v-show="letterHeadPdfFile" style="min-height:70vh" class="row">
                <div class="col-md-12">
                    <iframe class="iframe-container" id="setup-company-letterhead-pdf-iframe"></iframe>
                </div>
            </div>



        </div>

        <div v-show="activeTab === 'Logo'" class="form-tab-content">
            <div class="row">

                <div class="col-xxl-6 col-xl-10">

                    <fieldset class="mt-2"><legend>Logo</legend>

                        <logo-dropzone 
                            v-show="!record.logo"
                            id="company-logo-drop-zone-component" 
                            ref="company-logo-drop-zone-component" 
                            :options="logoDropOptions" 
                            :useCustomSlot=true 
                            @vdropzone-error="logoUploadError"
                            @vdropzone-success="logoUploaded"
                        >
                            <div class="dropzone-custom-content">
                                <h3 class="text-success">Drag and drop a file here</h3>
                                <div class="subtitle">...or click here to manually select a file</div>
                            </div>
                        </logo-dropzone>

                        <img v-show="record.logo" class="img-fluid border" style="max-height: 30vh;" :src="record.logo" alt="Company Logo">

                        <div v-show="record.logo" class="mt-3 text-right">
                            <button class="btn btn-success btn-sm d-inline-block mr-2" @click="replaceLogo" title="Change the Company logo"><i class="fa fa-refresh mr-2"></i>Replace</button>
                            <button class="btn btn-danger btn-sm d-inline-block" @click="deleteLogo" title="Delete the Company logo"><i class="fa fa-times mr-2"></i>Delete</button>
                        </div>


                    </fieldset>

                </div>

            </div>
        </div>

        <div v-show="activeTab === 'Email'" class="form-tab-content">
            <div class="row">
                <div class="col-md-12">

                    <h4>Reasons to your an Email System like Mailgun</h4>
                    <p>Blocked by your hosting provider while sending</p>
                    <p>Reached the email sending rate limit set by your hosting provider</p>
                    <p>Blocked by recipient server because of “bad reputation” of your hosting provider server</p>
                    <p>Went to SPAM or another automatically filtered folder</p>
                    <p>Went to GMail tab like “Promotions</p>
                    <p>Technical errors in the program</p>
                    <a href="https://laraveldaily.com/how-to-send-email-from-laravel-and-why-we-need-3rd-party-providers-for-it/">Source</a>

                </div>
            </div>

            <div class="row">

                <div class="col-xxl-6 mt-xxl-0 mt-xl-3">

                    <fieldset  style="background: lightgrey;" class="mt-3"><legend>Outgoing (SMTP) Server</legend>

                        <div class="form-group row">
                            <text-input 
                            _class="col-md-12" 
                            popOver="<h4>SMTP Server</h4>
                            <p>To send mail from Ettorney on your behalf, you need to specify the name of the SMTP Server your Company uses to send email.</p>
                            <p>You can get these details from your It dept, hosting company or by examining the settings you use in the email client you normally use to send email.</p>
                            "
                            :popOverContainer="'#' + id"
                            v-model="record.smtpServer" 
                            name="smtpServer" 
                            label="Server" 
                            :error="errors.smtpServer"/>
                        </div>

                        <div class="form-group row">
                            <text-input 
                            _class="col-md-6" 
                            popOver="<h4>SMTP Port</h4>
                            <p>An SMTP server will listen for incoming mail on a particular port.</p>
                            <p>This is typically 587, 465 or 25 but you can get these details from your It dept, hosting company or by examining the settings you use in the email client you normally use to send email.</p>
                            "
                            :popOverContainer="'#' + id"
                            v-model="record.smtpPort" 
                            name="smtpPort" 
                            label="Port" 
                            :error="errors.smtpPort"/>

                            <div class="col-md-6" style="align-self: flex-end;">

                                <button 
                                    :id="id + '-gmail-help-button'" 
                                    class="btn btn-danger form-button mb-1" 
                                    type="button" 
                                    @click="showGmailHelp"
                                >
                                <span title="Help on setting up access to a Gmail account">
                                    <i class="fa fa-question-circle fa-lg mr-2"></i>
                                    Gmail Help
                                </span>
                                </button>

                            </div>

                        </div>

                        <div class="form-group row">
                            <radio-buttons 
                                popOver="<h4>Encryption</h4>
                                    <p>Most Email Servers use either SSL or TLS (the latest) encryption.</p>
                                    <p>Before encryption was standard, many connections between an email client and the server were done insecurely. 
                                    This put personal information sent via email in danger of being intercepted and stolen. 
                                    Encyption reduces this risk by encrypting (or scrambling) the message when it is sent from the Email server to Ettorney.
                                    </p>
                                    <p>If your SMTP server uses encryption, specify the type of encryption it uses.</p>"
                                :popOverContainer="'#' + id"
                                _class="col-md-12" 
                                :record="record" 
                                column="smtpEncryption" 
                                name="smtpEncryption" 
                                :buttons="[
                                    {value:'None', text: 'None'},
                                    {value:'tls', text: 'TLS'},
                                    {value:'ssl', text: 'SSL'},
                                ]" 
                                label="Encryption" 
                                :error="errors.smtpEncryption"
                            />
                        </div>

                        <div class="form-group row">
                            <radio-buttons 
                                popOver="<h4>Authentication</h4>
                                    <p>Typically an Email Server requires a user to login to the server to send and receive email messages.</p>
                                    <p>If your server requires authentication, each Employee must have an SMTP username and password.</p>
                                    <p>Your user name and password can be specified below, but you must go to <em>Employees</em> and enter the SMTP username and password for each Employee (so they can send email messages using their credentials).</p>"
                                :popOverContainer="'#' + id"
                                _class="col-md-12" 
                                :record="record" 
                                column="smtpAuthentication" 
                                name="smtpAuthentication" 
                                :buttons="[
                                    {value:'Yes', text: 'Yes'},
                                    {value:'No', text: 'No'},
                                ]" 
                                label="Authentication" 
                                :error="errors.smtpAuthentication"
                                @change="authenticationChanged"
                            />
                        </div>

                        <div v-if="record.smtpAuthentication === 'Yes'" class="form-group row">
                            <text-input _class="col-md-12" 
                                popOver="<h4>User Name</h4>
                                <p>To login to the the Email Server, you need to provide a user name and password.</p>
                                <p>The user name is often just your email addres, but you can get these details from your It dept, hosting company or by examining the settings you use in the email client you normally use to send email.</p>
                                "
                                :popOverContainer="'#' + id"
                                v-model="employee.smtpUserName" 
                                name="smtpUserName" 
                                label="User Name"
                                @change="smptLoginDetailsChanged"
                            />
                        </div>

                        <div v-if="record.smtpAuthentication === 'Yes'" class="form-group row">
                            <text-input _class="col-md-12" 
                                v-model="employee.smtpPassword" 
                                name="smtpPassword" 
                                label="Password"
                                @change="smptLoginDetailsChanged" 
                            />
                        </div>


                        <div class="text-right">
                            <button v-show="record.smtpServer" 
                                :id="id + '-test-outgoing-email-button'" 
                                class="btn btn-danger form-button mt-1" 
                                type="button" 
                                @click="testOutgoingServer"
                            >
                            <span title="Check if you can login to the Outgoing Email Server">
                                <i class="fa fa-cog fa-lg mr-2"></i>Test Connection
                            </span>
                            </button>
                        </div>


                    </fieldset>

                </div>

                <div class="col-xxl-6 mt-xxl-0 mt-xl-3">

                    <fieldset  style="background: lightgrey;" class="mt-3"><legend>Incoming (IMAP) Server</legend>

                        <div class="form-group row">
                            <text-input 
                            _class="col-md-12" 
                            popOver="<h4>Incoming Server</h4>
                            <p>To import emails into Ettorney, you need to specify the name of the Email Server your Company uses to receive emails.</p>
                            <p>Ettorney uses the Imap protocol to retrieve messages so please ensure Imap is enabled on the Email Server (although it usually is by default).</p>
                            <p>You can get these details from your It dept, hosting company or by examining the settings you use in you email client.</p>
                            "
                            :popOverContainer="'#' + id"
                            v-model="record.incomingServer" 
                            name="incomingServer" 
                            label="Server" 
                            :error="errors.incomingServer"/>
                        </div>

                        <div class="form-group row">
                            <text-input 
                            _class="col-md-6" 
                            popOver="<h4>Type</h4>
                            <p>An email server will listen for requests to retrieve mail on a particular port.</p>
                            <p>This is typically 993 or 995 but you can get these details from your It dept or hosting company.</p>
                            "
                            :popOverContainer="'#' + id"
                            v-model="record.incomingPort" 
                            name="incomingPort" 
                            label="Port" 
                            :error="errors.incomingPort"/>
                        </div>

                        <div class="form-group row">
                            <radio-buttons 
                                popOver="<h4>Encryption</h4>
                                    <p>An Email Server typically requires some form of encryption on the incoming ports 993 or 995.</p>
                                    <p>Most Email Servers use SSL encryption.</p>
                                    <p>Before encryption was standard, many connections between an email client and the server were done insecurely. 
                                    This put personal information sent via email in danger of being intercepted and stolen. 
                                    Encyption reduces this risk by encrypting (or scrambling) the message when it is sent from the Email server to Ettorney.
                                    </p>
                                    <p>If your incoming email server uses encryption, specify the type of encryption it uses.</p>"
                                :popOverContainer="'#' + id"
                                _class="col-md-12" 
                                :record="record" 
                                column="incomingEncryption" 
                                name="incomingEncryption" 
                                :buttons="[
                                    {value:'None', text: 'None'},
                                    {value:'ssl', text: 'SSL'},
                                    {value:'tls', text: 'TLS'},
                                ]" 
                                label="Encryption" 
                                :error="errors.incomingEncryption"
                            />
                        </div>

                        <div class="text-right">
                            <button v-show="record.incomingServer" 
                            :id="id + '-test-incoming-email-button'" 
                            class="btn btn-danger form-button mt-1" 
                            type="button" 
                            @click="testIncomingServer"
                            >
                            <span title="Check if you can login to the Incoming Email Server">
                                <i class="fa fa-cog fa-lg mr-2"></i>Test Connection</span>
                            </button>
                        </div>


                    </fieldset>

                </div>
            </div>
        </div>

    </div>

    <div class="modal-footer justify-content-between">
        <div/>
        <div>
            <button :id="id + '-ok-button'" class="btn btn-success form-button mr-2" @click="submitForm" type="button" title="Save Settings"><i class="fa fa-check-circle fa-lg mr-2"></i>OK</button>
        </div>
    </div>

</div>

</template>

<script>

import vueDropzone from "vue2-dropzone";

export default {

    components: {
        logoDropzone: vueDropzone,
        letterheadDropzone: vueDropzone,
    },

    data() {
        return {
            id: 'setup-company',
            activePage: 'LetterHead',
            activeTab: null,
            record: {},
            employee: {}, 
            errors: {},
            logoDropOptions: {
                url: "/file/selected",
                maxFilesize: 5, // 5MB
                thumbnailWidth: 600,
                thumbnailMethod: 'contain',
                acceptedFiles: 'image/*'
            },
            letterHeadPdfFile: null,

            letterHeadDropOptions: {
                url: "/file/selected",
                maxFilesize: 5, // 5MB
                createImageThumbnails: false,
                acceptedFiles: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            },
            tabs: [
                {
                    pageName: "LetterHead",
                    title: "Letterhead",
                    iconClass: '',
                    visible: true,
                    active: true,
                },
                {
                    pageName: "Logo",
                    title: "Logo",
                    iconClass: '',
                    visible: true,
                    active: false,
                },
                {
                    pageName: "Email",
                    title: "Email Server",
                    iconClass: '',
                    visible: true,
                    active: false,
                },
            ]
        }
    },

    watch: {
        
        activeTab(newValue) {

            $('#' + this.id + ' .popover-icon').popover();

            if ( newValue === "LetterHead") {

                this.letterHeadPdfFile = root.lolSettings.letterheadpdffile;

            } else if ( newValue === "Email") {

                this.employee = root.currentEmployee;


            }

        },

        letterHeadPdfFile: function(newValue) {

            $('#setup-company-letterhead-pdf-iframe')[0].src = '';

            if ( newValue ) {
                setTimeout(() => {
                    
                    $('#setup-company-letterhead-pdf-iframe')[0].src = newValue;
                    
                });
            }
            
        }

    },

    methods: {

        smptLoginDetailsChanged() {

            axios.post('/employees/saveSmtpDetails', this.employee)
            
            .then(response => {

                if (response.data.error) { 
                    showError( 'Error', response.data.error);
                }

            }).catch(error => { 

                showError('Error',error);

            });

        },

        authenticationChanged() {   

            // Make sure the pop up works when this is unhidden
            if (this.record.smtpAuthentication === 'Yes') {
                setTimeout(() => {
                    $('#' + this.id + ' .popover-icon').popover();
                }, 1000);
            }
        },

        testIncomingServer() {

            if ( this.record.smtpAuthentication === 'Yes' && (!this.employee.smtpUserName || !this.employee.smtpPassword) ) {

                showError('Email Server Login Details Required','<p>Please insert your User Name and Password and try again.</p>');
                
            } else {

                let params = {
                    incomingServer: this.record.incomingServer,
                    incomingPort: this.record.incomingPort,
                    incomingEncryption: this.record.incomingEncryption,
                    userName: this.employee.smtpUserName,
                    password: this.employee.smtpPassword,
                };

                this.testIncomingMailServer( params );

            }
        },

        testIncomingMailServer( params ) {

            root.$snotify.simple('Checking incoming server', 'Please wait...', { timeout: 0, icon: 'img/cogs.gif' });

            axios.post('/mail/testIncomingServer',params)

            .then(response => {

                root.$snotify.clear();

                if (response.data.error) {

                    showError('Email Server Error',response.data.error);

                } else {

                    root.$snotify.simple('Connected to Incoming Email Server', 'Success', { timeout: 3000, icon: 'img/check.png' });

                }

            }).catch(error => { 

                showError('Error',error);

            });

        },

        testOutgoingServer() {

            if ( this.record.smtpAuthentication === 'Yes' && (!this.employee.smtpUserName || !this.employee.smtpPassword) ) {

                showError('Email Server Login Details Required','<p>Please insert your User Name and Password and try again.</p>');

            } else {

                axios.get('/employees/get-current')

                .then(response => {

                    let params = {
                        smtpServer: this.record.smtpServer,
                        smtpPort: this.record.smtpPort,
                        smtpEncryption: this.record.smtpEncryption,
                        smtpUserName: this.employee.smtpUserName,
                        smtpPassword: this.employee.smtpPassword,
                        email: response.data.email,
                        name: response.data.name,
                    };

                    this.testOutgoingMailServer( params );

            }).catch(error => { 

                showError('Error',error);

            });


            }


        },

        testOutgoingMailServer( params ) {

                root.$snotify.simple('Sending test email to ' + params.email, 'Please wait...', { timeout: 0, icon: 'img/cogs.gif' });

                axios.post('/mail/testOutgoingServer',params)

                .then(response => {

                    root.$snotify.clear();

                    if (response.data.error) {

                        showError('Email Server Error',response.data.error);

                    } else {

                        root.$snotify.simple('A test message was sent to ' + params.email + '. Check your inbox to see if you received the email.', 'Sent Email', { timeout: 3000, icon: 'img/check.png' });

                    }

            }).catch(error => { 

                showError('Error',error);

            });

        },

        showGmailHelp() {

            axios.post('/help/get', {
                fileName: 'gmail_imap.html'
            })

            .then(response => {

                if (response.data.error) {

                    showError('An error was encountered retrieving a help file',response.data.error);

                } else {

                    showHelp('Setting up email access to a Gmail account', response.data.contents);//, sizeClass);

                }
            }).catch(error => { 

                showError('Error',error);

            });

        },

        async letterHeadUploaded(file) {

            this.letterHeadPdfFile = '';// Clear this in case they upload the same file name

            var formData = new FormData();

            formData.append("file", file);
            formData.append("fileName", file.name);
            formData.append("folder", 'letterhead');

            let response = await axios.post('/file/upload', formData, {
                headers: {
                    'Content-Type': 'multipart/form-data'
                }
            });

            if (response.data.error) {

                showError('Error uploading document',response.data.error);

            } else {

                root.lolSettings.letterheadfilename = response.data.url;

                const convertOptions = {
                    destinationPath: 'letterhead',
                    docxFileName: file.name,
                    source: response.data.url,
                    sourceLocation: 'cloud',
                };

                let convertResponse = await convertToPdf(convertOptions);

                if ( convertResponse.error ) {

                    showError('PDF Conversion Error',convertResponse.error);

                } else {

                    root.lolSettings.letterheadpdffile = this.letterHeadPdfFile = convertResponse.url;

                    this.storeLetterHead();

                }

            }

        },

        storeLetterHead() {

            axios.post('/lolsettings/update', {
                recordid: root.lolSettings.recordid,
                letterheadfilename: root.lolSettings.letterheadfilename,
                letterheadpdffile: root.lolSettings.letterheadpdffile,
            })

            .then(response => {

                if (response.data.errors) {

                    showError('Error updating letterhead settings',response.data.errors);

                // } else {

                //     root.lolSettings = this.$root.lolSettings = response.data.data[0];

                }

            }).catch(error => { 

                showError('Error',error);

            });

        },

        downloadLetterHead() {

            root.downloadObject(root.lolSettings.letterheadfilename,'application/vnd.openxmlformats-officedocument.wordprocessingml.document');

        },

        replaceLetterHead() {

            this.deleteLetterHead();

            $('#company-letterhead-drop-zone-component').click();

        },

        deleteLetterHead() {

            this.$refs['company-letterhead-drop-zone-component'].removeAllFiles();

            root.lolSettings.letterheadfilename = null;
            root.lolSettings.letterheadpdffile = this.letterHeadPdfFile = null;

            this.storeLetterHead();

        },

        letterHeadUploadError(file, message, xhr)  {

            showError('Error uploading letterhead', message);

            this.$refs['company-letterhead-drop-zone-component'].removeAllFiles();

        },

        logoUploaded(file) {

            var formData = new FormData();

            formData.append("file", file);
            formData.append("fileName", file.name);
            formData.append("folder", 'logo');

            axios.post('/file/upload', formData, {
                headers: {
                    'Content-Type': 'multipart/form-data'
                }
            })

            .then(response => {

                if (response.data.error) {

                    showError('Error uploading logo',response.data.error);

                } else {

                    root.$snotify.simple('The Logo uploaded successfully', 'Success', { icon: 'img/check.png' });

                    axios.post('/lolsettings/update', {
                        recordid: root.lolSettings.recordid,
                        logo: response.data.url,
                    })

                    .then(response => {

                        if (response.data.errors) {

                            showError('Error saving logo',response.data.errors);

                        } else {

                            root.lolSettings = this.$root.lolSettings = response.data.data[0];

                            root.templateData.company.logo = response.data.data[0].url;

                        }
                    });

                }

            }).catch(error => { 

                showError('Error',error);

            });

        },

        replaceLogo() {

            this.deleteLogo();

            $('#company-logo-drop-zone-component').click();

        },

        deleteLogo() {

            this.$refs['company-logo-drop-zone-component'].removeAllFiles();
            this.record.logo = root.lolSettings.logo = this.$root.lolSettings.logo = null;

        },

        logoUploadError(file, message, xhr)  {

            showError('Error uploading logo', message);

            this.$refs['company-logo-drop-zone-component'].removeAllFiles();

        },


        renderDate(format) {

            return format + ' (' + moment().format(format) + ')';

        },

        submitForm() {

            console.log("submitForm"); return; // Don't need this

            /*axios.post('/lolsettings/update', this.record)

            .then(response => {

                if (response.data.errors) {

                    showError('Error saving Settings',response.data.errors);

                } else {

                    root.$snotify.simple('The Settings were updated successfully', 'Success', { icon: 'img/check.png' });

                    root.lolSettings = this.$root.lolSettings = response.data.data[0];

                }

            }).catch(error => { 

                showError('Error',error);

            });*/

        },

        hide() {

            this.$root.$refs['right-hand-tab-container'].$refs['right-hand-tabs'].closePage(this.activePage);

        },


    },    

}
</script>

<style src='vue2-dropzone/dist/vue2Dropzone.min.css'></style>
